app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /zaenfhrpitnfzdlfsjgkjs^g

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"