parameters:
    #parameter_name: value

services:

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments:
            ['%cv_directory%', "@security.token_storage" ]

    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments:
            ['%img_directory%', "@security.token_storage" ]

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.profile.form.type:
        class: AppBundle\Form\ProfileType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_edit_profile }

    app.registration_listener:
        class: AppBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    app.image_uploader:
        class: AppBundle\Service\ImageUpload
        arguments: ['%img_directory%']

    app.doctrine_image_listener:
        class: AppBundle\EventListener\ImageUploadListener
        arguments: ['@app.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    app.fullcalendar_listener:
       class: AppBundle\Listener\LoadDataListener
       tags:
           - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }